### ISSUE TITLE
Can't add API key

### ISSUE THREAD

**Issue by teameh** [jenkinsci/violation-comments-to-gitlab-plugin#15]
Hi,

I'm trying to set up this plugin but I can't add any credentials. The dropdown stays empty. 

![image](https://user-images.githubusercontent.com/1330668/40116102-dfa4d910-5912-11e8-9305-e24c8a1cc595.png)

Even after clicking the 'add' button and adding all kids of keys nothing shows up in the list. 

The weird thing is that the general git plugin does recognise the credentials and works fine: 

![image](https://user-images.githubusercontent.com/1330668/40116232-4535f7aa-5913-11e8-9f9e-4436e7b29270.png)

**Comment by tomasbjerre** [comment]
What version of Jenkins och what version of the plugin?

**Comment by teameh** [comment]
Jenkins: 2.89.4
GitLab Plugin: 1.5.5 
Violation Comments to GitLab Plugin: 2.0

**Comment by tomasbjerre** [comment]
Are you selecting **Kind** as **secret text** when adding the credential?

**Comment by teameh** [comment]
Check. That was the only one that I didn't try yet. Thanks that worked. 

However it's not clear to me what to put in the other fields:


![image](https://user-images.githubusercontent.com/1330668/40180507-465792b8-59e7-11e8-96d3-51acd4ba77bd.png)

There's no project Id defined in gitlab plugin's https://github.com/jenkinsci/gitlab-plugin#defined-variables

If I just put in the project number (270) and `{gitlabMergeRequestIid}` as Merge Request Iid i get:

```
Will comment PR https://xxxxx.xxxxx/ 270 {gitlabMergeRequestIid}
java.lang.NumberFormatException: For input string: "{gitlabMergeRequestIid}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
```

**Comment by tomasbjerre** [comment]
Yes you can hardcode project id. As an integer or a string like: tomas.bjerre85%2Fviolations-test

Ypu are missing the dollar sign in merge request iid.

**Comment by teameh** [comment]
> Yes you can hardcode project id. As an integer or a string like: tomas.bjerre85%2Fviolations-test

Check

> Ypu are missing the dollar sign in merge request iid.

Haha yeah noticed it, thanks. 

Still failed until i ticked "private token" maybe that needs some documentation.
