### ISSUE TITLE
Support commentOnlyChangedContentContext

### ISSUE THREAD

**Issue by WonderCsabo** [jenkinsci/violation-comments-to-gitlab-plugin#19]
Expected: if the `commentOnlyChangedContent` parameter is set to `true`, only the violations for changed lines should be reported.

Actual: it seems if the violation is inside the diff, it is still reported, despite if the line was actually changed or not.

Example:

<img width="961" alt="screenshot 2019-03-04 at 15 35 44" src="https://user-images.githubusercontent.com/480485/53740300-2f3b2d00-3e94-11e9-929c-53ab21d9dac6.png">

You can see that a violation was reported for line 5 (the line with ellipsis), but that line actually was not changed by the commits.

**Comment by tomasbjerre** [comment]
This is intended. I would argue that it is likely that a changed line may introduce a problem that is reported on a nearby line. Not necessarily reported on the exact line that was changed. 

Any violation within the patch, reported by GitLab, will be reported. The patch being what a human would see when viewing the merge request diff in the GUI. Implemented like this:

 * https://github.com/tomasbjerre/violation-comments-to-gitlab-lib/blob/master/src/main/java/se/bjurr/violations/comments/gitlab/lib/GitLabCommentsProvider.java#L279
 * https://github.com/tomasbjerre/violation-comments-lib/blob/master/src/main/java/se/bjurr/violations/comments/lib/PatchParser.java

**Comment by WonderCsabo** [comment]
Could be relevant, but could be totally irrelevant. You cannot know. Since the flag is about the *changed* code, IMHO it should be reported for the *changed* code, and not other, nearby parts as well.

**Comment by tomasbjerre** [comment]
The [Bitbucket Server plugin](https://github.com/jenkinsci/violation-comments-to-stash-plugin) has a `commentOnlyChangedContentContext` config that can be set to `1` to only comment on the exact line. That feature can be added here to solve this issue.

**Comment by WonderCsabo** [comment]
Good idea!

**Comment by shyingsheng** [comment]
Hi Tomas,
Do you have the ETA when this enhancement can be implemented?

**Comment by tomasbjerre** [comment]
No. Pull requests are welcome.

**Comment by Kylmakalle** [comment]
Looks like it's supported now
https://github.com/jenkinsci/violation-comments-to-gitlab-plugin/commit/7cbdf2565be1ea05b1b2c1aba1b990efbee4aec1

**Comment by tomasbjerre** [comment]
yes this is available now.

**Comment by shyingsheng** [comment]
Hi Tomas，
Firstly very happy to know that this enhancement was implemented in 2.49.
But in release page, latest one is 2.47, how can I upgrade to 2.49 via jenkins plugin manager?

**Comment by tomasbjerre** [comment]
I made a new release now, should be available within hours.

**Comment by shyingsheng** [comment]
Many many thanks, new release is available now.
