### ISSUE TITLE
Jenkins pipeline-syntax entry does not generate correctly

### ISSUE THREAD

**Issue by wejrox** [jenkinsci/violation-comments-to-gitlab-plugin#29]
It may be a good idea to look at old issues, both closed and open.

Some recurring problems are:

 * The user did not perform the merge before doing the analysis.
 * No violations were reported because:
   * The user tested the plugin on a PR that did not introduce any new violations.
   * The user had both `createSingleFileComments` and `createCommentWithAllSingleFileComments` set to `false`

When reporting a bug, please **try** to provide as much information as possible.

 * Plugin version used.
2.45
 * Jenkins version used.
2.176.4
 * Your configuration.
   * Pipeline script or screenshot.
![Capture](https://user-images.githubusercontent.com/23255412/105278956-ab5ecb00-5bfa-11eb-973b-920dc2733f64.PNG)
 * Expected result and actual result.
I expected that the pipeline generator would be able to display a snippet that I could paste into my jenkinsfile, with the details set up. Instead, I received what seems to be an object stringification.
 * Any information from the logs:
   * Jenkins log: http://jenkins-server/log/
   No relevant logs
   * Build log.
   No Build was able to be performed since it couldn't generate the definition.

**Comment by tomasbjerre** [comment]
Thanks for reporting.
I can confirm this.
You may want to use the command line tool instead:
https://www.npmjs.com/package/violation-comments-to-gitlab-command-line

**Comment by tomasbjerre** [comment]
Should be fixed in 2.46. Open issue again if not working.
